// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/assets" | "/assets/[symbol]" | "/candidates/[id]" | "/copilot" | "/dashboard" | "/experiments" | "/experiments/[id]" | "/journal" | "/market-intelligence" | "/mission-control" | "/paper" | "/paper/deployments" | "/reports" | "/research" | "/research-intelligence" | "/settings" | "/strategies" | "/strategies/[name]" | "/validation" | "/validation/[id]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/assets": {}
  "/assets/[symbol]": { "symbol": string; }
  "/candidates/[id]": { "id": string; }
  "/copilot": {}
  "/dashboard": {}
  "/experiments": {}
  "/experiments/[id]": { "id": string; }
  "/journal": {}
  "/market-intelligence": {}
  "/mission-control": {}
  "/paper": {}
  "/paper/deployments": {}
  "/reports": {}
  "/research": {}
  "/research-intelligence": {}
  "/settings": {}
  "/strategies": {}
  "/strategies/[name]": { "name": string; }
  "/validation": {}
  "/validation/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
